#
# Makefile for the virt2real platform
#
obj-$(CONFIG_V2R_PINS)		+= v2r_pins.o
obj-$(CONFIG_V2R_GPIO)		+= v2r_gpio.o
obj-$(CONFIG_V2R_ADC)		+= v2r_adc.o
obj-$(CONFIG_V2R_SWPWM)		+= v2r_sw_pwm.o
obj-$(CONFIG_V2R_EXTPWM)        += v2r_extpwm.o
obj-$(CONFIG_V2R_GPIOEVENT)     += gpio-event-drv.o
obj-$(CONFIG_V2R_PPM)     	+= v2r_ppm.o
